## Database Properties
spring.datasource.url=jdbc:mysql:///usersdb?cloudSqlInstance=project-8774d229-bcf5-44b8-9d5:us-central1:users-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
